name: Build Extensions

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install --global web-ext@6.8.0
          
      - name: Prepare Chrome version
        run: |
          mkdir -p chrome
          cp -r icons chrome/
          cp -r image chrome/
          cp -r lib chrome/
          cp -r _locales chrome/
          cp popup.html chrome/
          cp popup.js chrome/
          cp content.js chrome/
          cat manifest.json | jq 'del(.browser_specific_settings)' > chrome/manifest.json
          
      - name: Build Chrome extension
        run: |
          cd chrome
          zip -r ../Chrome.zip *
          
      - name: Prepare Firefox version  
        run: |
          mkdir -p firefox
          cp -r icons firefox/
          cp -r image firefox/
          cp -r lib firefox/
          cp -r _locales firefox/
          cp popup.html firefox/
          cp popup.js firefox/
          cp content.js firefox/
          cp manifest.json firefox/
          
      - name: Build and Sign Firefox Extension
        run: |
          cd firefox
          web-ext sign --api-key=${{ secrets.AMO_JWT_ISSUER }} --api-secret=${{ secrets.AMO_JWT_SECRET }} --channel=unlisted
          mv web-ext-artifacts/*.xpi ../Firefox.xpi
        env:
          AMO_JWT_ISSUER: ${{ secrets.AMO_JWT_ISSUER }}
          AMO_JWT_SECRET: ${{ secrets.AMO_JWT_SECRET }}
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          body: |
            抖音直播直链解析浏览器扩展 `${{ github.ref_name }}` 版本
            
            ### 安装说明
            - Chrome版本: 下载 `Chrome.zip` ，解压后在扩展管理页面通过"加载已解压的扩展程序"安装
            - Firefox版本: 下载 `Firefox.xpi`，直接拖放到Firefox中安装
          draft: false
          prerelease: false
          
      - name: Upload Chrome Extension
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Chrome.zip
          asset_name: Chrome.zip
          asset_content_type: application/zip
          
      - name: Upload Firefox Extension  
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Firefox.xpi
          asset_name: Firefox.xpi
          asset_content_type: application/x-xpinstall

      - name: Clean up
        if: always()
        run: |
          rm -rf chrome firefox web-ext-artifacts