name: Build Extensions

on:
  push:
    tags:
      - 'v*' # 当推送v开头的tag时触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: |
          npm install --global web-ext
          
      - name: Prepare Chrome version
        run: |
          mkdir -p chrome
          # 复制所有必要文件
          cp -r icons chrome/
          cp -r lib chrome/
          cp -r _locales chrome/
          cp popup.html chrome/
          cp popup.js chrome/
          cp content.js chrome/
          # 移除Firefox特定配置
          cat manifest.json | jq 'del(.browser_specific_settings)' > chrome/manifest.json
          
      - name: Build Chrome extension
        run: |
          cd chrome
          zip -r ../douyin-live-parser-chrome.zip *
          
      - name: Prepare Firefox version  
        run: |
          mkdir -p firefox
          # 复制所有必要文件
          cp -r icons firefox/
          cp -r lib firefox/
          cp -r _locales firefox/
          cp popup.html firefox/
          cp popup.js firefox/
          cp content.js firefox/
          cp manifest.json firefox/
          
      - name: Build Firefox extension
        run: |
          cd firefox
          # 指定输出文件名
          web-ext build --artifacts-dir ../ --filename douyin-live-parser.xpi
          cd ..
          # 确保文件存在
          if [ ! -f "douyin-live-parser.xpi" ]; then
            echo "Firefox extension build failed"
            exit 1
          fi
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            抖音直播直链解析浏览器扩展 ${{ github.ref }} 版本
            
            ### 安装说明
            - Chrome版本: 下载douyin-live-parser-chrome.zip，解压后在扩展管理页面通过"加载已解压的扩展程序"安装
            - Firefox版本: 下载douyin-live-parser.xpi，直接拖放到Firefox中安装
          draft: false
          prerelease: false
          
      - name: Upload Chrome Extension
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./douyin-live-parser-chrome.zip
          asset_name: douyin-live-parser-chrome.zip
          asset_content_type: application/zip
          
      - name: Upload Firefox Extension  
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./douyin-live-parser.xpi
          asset_name: douyin-live-parser.xpi
          asset_content_type: application/x-xpinstall

      - name: Clean up
        if: always()
        run: |
          rm -rf chrome firefox web-ext-artifacts