name: Build Firefox Extension

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-firefox:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install web-ext
        run: npm install --global web-ext@6.8.0 #或者移除版本限制 npm install --global web-ext

      - name: Prepare Firefox version
        run: |
          mkdir -p firefox
          cp -r icons firefox/
          cp -r lib firefox/
          cp -r _locales firefox/
          cp popup.html firefox/
          cp popup.js firefox/
          cp content.js firefox/
          cp manifest.json firefox/

      - name: Build Firefox extension (XPI)
        run: |
          cd firefox
          web-ext build
          mv web-ext-artifacts/*.xpi ../douyin-live-parser.xpi
        
      - name: Upload Firefox XPI as artifact
        uses: actions/upload-artifact@v3
        with:
          name: douyin-live-parser-firefox
          path: douyin-live-parser.xpi
